### ISSUE TITLE
I can't uninstall firim,and fastlane is crashed...

### ISSUE THREAD

**Issue by madordie** [whlsxl/firim#4]
[issues](https://github.com/fastlane/fastlane/issues/7801)

**Comment by whlsxl** [comment]
Hi @madordie 
Have you try to delete the line `gem 'fastlane-plugin-firim'` in `Pluginfile`
After that, try to uninstall `firim` by `gem uninstall firim`.
Feel free to tell me if it still unsolved.

**Comment by whlsxl** [comment]
I think I fixed the bug.
If this is the problem that happen to you

**Comment by whlsxl** [comment]
You can update the version of `firim`

**Comment by madordie** [comment]
It works fine。 thx. 👍

**Comment by madordie** [comment]
```
  519  sudo gem install firim
  520  fastlane --version
  521  fastlane env
  522  gem uninstall firim
  523  sudo gem uninstall gem
  524  sudo gem uninstall firim
  525  fastlane env
```
 ** then **
```
$ fastlane env
[11:42:56]: Generating fastlane environment output, this might take a few seconds...
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/dependency.rb:296:in `to_specs': Could not find 'firim' (~> 0) among 138 total gem(s) (Gem::LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1209:in `block in activate_dependencies'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1198:in `each'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1198:in `activate_dependencies'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1180:in `activate'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems.rb:186:in `rescue in try_activate'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems.rb:183:in `try_activate'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:132:in `rescue in require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:144:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.7.0/fastlane/lib/fastlane/fastlane_require.rb:10:in `install_gem_if_needed'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.7.0/fastlane/lib/fastlane/plugins/plugin_manager.rb:276:in `block in load_plugins'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.7.0/fastlane/lib/fastlane/plugins/plugin_manager.rb:268:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.7.0/fastlane/lib/fastlane/plugins/plugin_manager.rb:268:in `load_plugins'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.7.0/fastlane/lib/fastlane/environment_printer.rb:56:in `print_loaded_plugins'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.7.0/fastlane/lib/fastlane/environment_printer.rb:27:in `get'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.7.0/fastlane/lib/fastlane/environment_printer.rb:4:in `output'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.7.0/fastlane/lib/fastlane/commands_generator.rb:223:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.3/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.3/lib/commander/runner.rb:446:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.7.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.3/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.7.0/fastlane/lib/fastlane/commands_generator.rb:293:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.7.0/fastlane/lib/fastlane/commands_generator.rb:36:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.7.0/fastlane/lib/fastlane/cli_tools_distributor.rb:59:in `take_off'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.7.0/bin/fastlane:15:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
```

** BUT **
```
  529  sudo gem install firim
  530  fastlane env
```
and `fastlane` is working properly
** SO ** I can not remove firim😭😭😭

**Comment by whlsxl** [comment]
Could you show me your `Pluginfile` file?
`fastlane-plugin-firim` is a Plugin for `fastlane`.
 If you install `fastlane-plugin-firim`, that depend on `firim`
`fastlane` didn't depend on `firim`

**Comment by whlsxl** [comment]
Try use `gem dependency fastlane` to find the dependency tree

**Comment by madordie** [comment]
👍 👍 👍   It works fine,  thx
