### ISSUE TITLE
Could action "firim" support operating system "android"?

### ISSUE THREAD

**Issue by Chittyo** [whlsxl/firim#7]
Could action "firim" support operating system "android"? 
When I used "fastlane-plugin-firim" uploading apk to fir.im , it prompted "Action 'firim' isn't known to support operating system 'android'." and warning "Unexpected middleware set after the adapter. This won't be supported from Faraday 1.0." 
How can I do?

**Comment by whlsxl** [comment]
Sorry, I don't have android development environment.
could you give me more error information.

**Comment by xwartz** [comment]
I created a pr to support andorid https://github.com/whlsxl/firim/pull/9

**Comment by whlsxl** [comment]
@xwartz could you help me to test working with fastlane, I have committed some new code.

**Comment by xwartz** [comment]
@whlsxl  

When i publish ipa, fastlane finished with errors:

```
/Users/xwartz/.rvm/gems/ruby-2.3.0/gems/firim-0.1.4/lib/firim/runner.rb:82:in `upload_binary_and_icon': [!] undefined method `[]' for nil:NilClass (NoMethodError)
	from /Users/xwartz/.rvm/gems/ruby-2.3.0/gems/firim-0.1.4/lib/firim/runner.rb:42:in `run'
	from /Users/xwartz/.rvm/gems/ruby-2.3.0/gems/fastlane-plugin-firim-0.1.0/lib/fastlane/plugin/firim/actions/firim_action.rb:15:in `run'
	from /Users/xwartz/.rvm/gems/ruby-2.3.0/gems/fastlane-2.78.0/fastlane/lib/fastlane/runner.rb:253:in `block (2 levels) in execute_action'
	from /Users/xwartz/.rvm/gems/ruby-2.3.0/gems/fastlane-2.78.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Users/xwartz/.rvm/gems/ruby-2.3.0/gems/fastlane-2.78.0/fastlane/lib/fastlane/runner.rb:231:in `block in execute_action'
	from /Users/xwartz/.rvm/gems/ruby-2.3.0/gems/fastlane-2.78.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'
	from /Users/xwartz/.rvm/gems/ruby-2.3.0/gems/fastlane-2.78.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
	from /Users/xwartz/.rvm/gems/ruby-2.3.0/gems/fastlane-2.78.0/fastlane/lib/fastlane/runner.rb:148:in `trigger_action_by_name'
	from /Users/xwartz/.rvm/gems/ruby-2.3.0/gems/fastlane-2.78.0/fastlane/lib/fastlane/fast_file.rb:148:in `method_missing'
	from Fastfile:32:in `block (2 levels) in parsing_binding'
	from /Users/xwartz/.rvm/gems/ruby-2.3.0/gems/fastlane-2.78.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/xwartz/.rvm/gems/ruby-2.3.0/gems/fastlane-2.78.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/xwartz/.rvm/gems/ruby-2.3.0/gems/fastlane-2.78.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/xwartz/.rvm/gems/ruby-2.3.0/gems/fastlane-2.78.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/xwartz/.rvm/gems/ruby-2.3.0/gems/fastlane-2.78.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
	from /Users/xwartz/.rvm/gems/ruby-2.3.0/gems/fastlane-2.78.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /Users/xwartz/.rvm/gems/ruby-2.3.0/gems/fastlane-2.78.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	from /Users/xwartz/.rvm/gems/ruby-2.3.0@global/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
	from /Users/xwartz/.rvm/gems/ruby-2.3.0@global/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
	from /Users/xwartz/.rvm/gems/ruby-2.3.0@global/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/xwartz/.rvm/gems/ruby-2.3.0/gems/fastlane-2.78.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:75:in `run!'
	from /Users/xwartz/.rvm/gems/ruby-2.3.0@global/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/xwartz/.rvm/gems/ruby-2.3.0/gems/fastlane-2.78.0/fastlane/lib/fastlane/commands_generator.rb:337:in `run'
	from /Users/xwartz/.rvm/gems/ruby-2.3.0/gems/fastlane-2.78.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /Users/xwartz/.rvm/gems/ruby-2.3.0/gems/fastlane-2.78.0/fastlane/lib/fastlane/cli_tools_distributor.rb:98:in `take_off'
	from /Users/xwartz/.rvm/gems/ruby-2.3.0/gems/fastlane-2.78.0/bin/fastlane:20:in `<top (required)>'
	from /Users/xwartz/.rvm/gems/ruby-2.3.0/bin/fastlane:23:in `load'
	from /Users/xwartz/.rvm/gems/ruby-2.3.0/bin/fastlane:23:in `<main>'
	from /Users/xwartz/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
	from /Users/xwartz/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by whlsxl** [comment]
@xwartz do you checkout the latest code?  The `lib/firim/runner.rb:82` is not in `upload_binary_and_icon` now 
<img width="769" alt="screen shot 2018-02-04 at 3 07 02 pm" src="https://user-images.githubusercontent.com/305995/35775100-4f5536b0-09bd-11e8-8dfd-d4af4ecffa80.png">

**Comment by xwartz** [comment]
我是用的最新代码的，pull 了你最新的改动。

0.0 你会中文的吧..

2018-02-04 15:09 GMT+08:00 Wang Hailong <notifications@github.com>:

**Comment by whlsxl** [comment]
@xwartz  会的-_-!
pull之后有重新编译么？
是用`fastlane` 提交 还是直接用`firim`命令行啊？
贴下命令

**Comment by xwartz** [comment]
我 pull 到自己的仓库之后，更改 pluginfile: gem 'fastlane-plugin-firim', git: '
https://github.com/xwartz/firim'

然后通过 fastlane install_plugins, 再执行 fastlane firim 的。

其实我不怎么会 ruby 的，以上操作还需要额外的编译吗？

2018-02-04 16:51 GMT+08:00 Wang Hailong <notifications@github.com>:

**Comment by whlsxl** [comment]
@xwartz 
我一般是直接编译gem 然后安装，
`firim`分成两个`gem`，其中`firim`是命令行程序`fastlane-plugin-firim`是连接`fastlane`的插件。安装方法如下：
在根目录
```
gem build firim.gemspec 
gem install firim-0.1.4.gem 
//编译安装firim
cd fastlane-plugin-firim/
gem build fastlane-plugin-firim.gemspec
gem install fastlane-plugin-firim-0.1.0.gem
//编译安装fastlane-plugin-firim
```
